### ISSUE TITLE
accompany post/tutorial/video?

### ISSUE THREAD

**Issue by notsureifkevin** [vranystepan/doks-traefik2-platform#18]
Greetings! I'm Kevin, Developer Advocate at Containous, the creators of Traefik, and this project came across our radar. I was curious if there was an accompanying blog post or other content that helps users understand some use-cases and examples of the project?

**Comment by kubopanda** [comment]
I think we can close this. I've pinged him and encouraged him to write a post. I'll put something on our agenda bc I feel like sharing tweets with a github link could inspire others to share, which gives us data points and more people to nurture into greater things. That's the impetus of me adding this to our editorial stuff to review. wdyt? Talk tomorrow. :)
